defaults:
  - data: cic_2018_v2
  - classifier: random_forest
  - _self_
  - path: default

seed: 42
name: exp
stage: all

grid_search:
  enabled: false
  scoring: f1_macro
  cv: 5

n_samples: null
run_id: 0

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
